### ISSUE TITLE
Ruby 1.9.3 compatibility

### ISSUE THREAD

**Issue by lfigueira** [inukshuk/citeproc-ruby#13]
Hi, 

I've been (very happily) using the citeproc-ruby gem, together with bibtex-ruby, for the last year, until I needed to update my Ruby version to 1.9.3... When I try to process an entry, I get the following: 

```
1.9.3-p125 :015 > CiteProc.process(book)
NoMethodError: undefined method `stringify_keys' for {"delimiter"=>" ", "node"=>"CSL::Nodes::Group"}:CSL::Nodes::Group
    from /Users/luisf/.rvm/gems/ruby-1.9.3-p125/gems/activerecord-3.2.10/lib/active_record/attribute_assignment.rb:69:in `assign_attributes'
```

I know that in the documentation you explicitly say that the version 0.0.x of this gem is not supposed to work on Ruby 1.9.3; I've already tried to run the new citeproc and citeproc-js gems, also with no success (I had issues installing the johnston gem).

I'd be very interested in continuing to use this gem with Ruby 1.9.3 - what are my options (if any)?

Many thanks! 

Luis
